version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: abhay/node_crud
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_live_db
      - PG_USER=abhay
      - PG_PASSWORD=6541
      - PG_HOST=node_db
    restart: always
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5435:5435"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=abhay
      - POSTGRES_PASSWORD=6541
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
